'use client'
import { useRef } from 'react'
import { AIProduct } from '@/lib/supabase'
import { useLang } from '@/lib/LangContext'
import { t } from '@/lib/i18n'

export default function ComparePanel({ products, onClose }: {
  products: AIProduct[]
  onClose: () => void
}) {
  const { lang } = useLang()
  const tx = (key: string) => t[key]?.[lang] ?? key
  const ko = lang === 'ko'
  const printRef = useRef<HTMLDivElement>(null)

  const fields = [
    { label: tx('manufacturer'),  key: 'manufacturer' },
    { label: tx('country'),       key: ko ? 'country_ko' : 'country' },
    { label: tx('category'),      key: ko ? 'category_main_ko' : 'category_main' },
    { label: tx('subcategory'),   key: ko ? 'category_sub_ko' : 'category_sub' },
    { label: 'Service Type',      key: ko ? 'service_type_ko' : 'service_type' },
    { label: 'Modality',          key: ko ? 'modality_ko' : 'modality' },
    { label: 'Service Region',    key: ko ? 'service_region_ko' : 'service_region' },
    { label: 'Pricing',           key: ko ? 'pricing_type_ko' : 'pricing_type' },
    { label: 'Monthly Fee',       key: 'monthly_fee_usd' },
    { label: 'API Pricing',       key: ko ? 'api_pricing_ko' : 'api_pricing' },
    { label: 'Accessibility',     key: ko ? 'accessibility_ko' : 'service_accessibility' },
    { label: tx('verification'),  key: ko ? 'verification_ko' : 'verification_status' },
  ]

  function handlePrint() {
    const printContent = printRef.current
    if (!printContent) return
    const win = window.open('', '_blank', 'width=1200,height=900')
    if (!win) return
    win.document.write(`
      <html>
      <head>
        <title>AI MAP — Compare Report</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: Arial, sans-serif; font-size: 9pt; color: #000; background: #fff; padding: 12mm; }
          h2 { font-size: 16pt; color: #007744; margin-bottom: 4px; }
          .subtitle { font-size: 8pt; color: #666; margin-bottom: 16px; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #f0f0f0; font-size: 8pt; padding: 6px 8px; border: 1px solid #ddd; text-align: center; font-weight: 600; }
          td { font-size: 8pt; padding: 5px 8px; border: 1px solid #eee; vertical-align: top; }
          td:first-child { background: #f8f8f8; font-weight: 600; color: #444; width: 120px; white-space: nowrap; }
          tr:nth-child(even) td { background: #fafafa; }
          tr:nth-child(even) td:first-child { background: #f0f0f0; }
          .badge { display: inline-block; padding: 1px 6px; border-radius: 99px; font-size: 7pt; border: 1px solid #ccc; }
          .badge-green { background: #e6fff2; border-color: #00aa55; color: #007733; }
          .badge-gray  { background: #f5f5f5; border-color: #ccc; color: #666; }
          .footer { margin-top: 16px; padding-top: 8px; border-top: 1px solid #ddd; font-size: 7pt; color: #999; text-align: center; }
          a { color: #0066cc; }
        </style>
      </head>
      <body>
        <h2>AI MAP — ${tx('compareTitle')} (${products.length})</h2>
        <div class="subtitle">GAIT 69: Global AI Index Taxonomy · DOI: 10.5281/zenodo.20248631 · © 2025 DO HUN, KIM</div>
        ${printContent.innerHTML}
        <div class="footer">Generated by AI MAP · ai-engine-app.vercel.app · ${new Date().toLocaleDateString()}</div>
      </body>
      </html>
    `)
    win.document.close()
    win.focus()
    setTimeout(() => { win.print(); win.close() }, 500)
  }

  const gridCols = `150px repeat(${products.length}, minmax(100px, 1fr))`

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 50,
        background: 'rgba(0,0,0,0.88)',
        display: 'flex', alignItems: 'flex-end', justifyContent: 'center',
      }}
      onClick={onClose}
    >
      <div
        style={{
          width: '100%', maxWidth: '1280px', margin: '0 12px 12px',
          background: 'var(--surface)', border: '1px solid var(--border)',
          borderRadius: '16px', padding: '24px',
          maxHeight: '92vh', overflowY: 'auto',
        }}
        onClick={e => e.stopPropagation()}
      >
        {/* 패널 헤더 */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px', flexWrap: 'wrap', gap: '8px' }}>
          <div>
            <h2 className="font-display text-2xl" style={{ color: 'var(--accent)' }}>
              {tx('compareTitle')} ({products.length}/{10})
            </h2>
            <p style={{ fontSize: '11px', color: '#555', marginTop: '2px', fontFamily: 'monospace' }}>
              GAIT 69 · DOI: 10.5281/zenodo.20248631 · © 2025 DO HUN, KIM
            </p>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              onClick={handlePrint}
              className="btn-ghost"
              style={{ border: '1px solid rgba(0,255,136,0.3)', color: 'var(--accent)', fontSize: '13px' }}
            >
              {tx('printBtn')}
            </button>
            <button onClick={onClose} className="btn-ghost">{tx('closeBtn')}</button>
          </div>
        </div>

        {/* 인쇄용 숨김 테이블 */}
        <div ref={printRef} style={{ display: 'none' }}>
          <table>
            <thead>
              <tr>
                <th></th>
                {products.map(p => (
                  <th key={p.id}>
                    {p.product_name}<br/>
                    <span style={{ fontWeight: 400, fontSize: '7pt' }}>{p.manufacturer}</span>
                    {p.official_url && <><br/><a href={p.official_url}>{p.official_url}</a></>}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {fields.map(f => (
                <tr key={f.key}>
                  <td>{f.label}</td>
                  {products.map(p => (
                    <td key={p.id}>{String((p as any)[f.key] ?? '-').replace(/^\d+[-\.]\s*/, '')}</td>
                  ))}
                </tr>
              ))}
              <tr>
                <td>{tx('activeVersions')}</td>
                {products.map(p => {
                  const vs = p.versions?.filter(v => v.is_active) || []
                  return <td key={p.id}>{vs.map(v => v.version_name).join(', ') || '-'}</td>
                })}
              </tr>
              <tr>
                <td>{tx('deprVersions')}</td>
                {products.map(p => {
                  const vs = p.versions?.filter(v => !v.is_active) || []
                  return <td key={p.id}>{vs.map(v => v.version_name).join(', ') || '-'}</td>
                })}
              </tr>
              <tr>
                <td>{tx('expertAnalysis')}</td>
                {products.map(p => (
                  <td key={p.id}>{ko ? (p.description_ko || p.description || '-') : (p.description || '-')}</td>
                ))}
              </tr>
            </tbody>
          </table>
        </div>

        {/* 화면 비교 테이블 */}
        {/* 제품명 헤더 */}
        <div style={{ display: 'grid', gridTemplateColumns: gridCols, gap: '10px', marginBottom: '12px', paddingBottom: '12px', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
          <div />
          {products.map(p => (
            <div key={p.id} style={{ textAlign: 'center' }}>
              <div style={{ fontWeight: 700, color: '#fff', fontSize: '12px', lineHeight: 1.3 }}>{p.product_name}</div>
              <div style={{ fontSize: '10px', color: '#666', marginTop: '2px' }}>{p.manufacturer}</div>
              {p.official_url && (
                <a href={p.official_url} target="_blank" rel="noopener noreferrer"
                  style={{ fontSize: '10px', color: 'var(--accent)', marginTop: '4px', display: 'block' }}>
                  🔗 {tx('officialSite')}
                </a>
              )}
            </div>
          ))}
        </div>

        {/* 필드 행들 */}
        {fields.map(f => (
          <div key={f.key} style={{ display: 'grid', gridTemplateColumns: gridCols, gap: '10px', padding: '7px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
            <div style={{ fontSize: '11px', color: '#666', fontFamily: 'monospace', display: 'flex', alignItems: 'center' }}>{f.label}</div>
            {products.map(p => (
              <div key={p.id} style={{ fontSize: '11px', color: '#ccc', textAlign: 'center' }}>
                {f.key === 'monthly_fee_usd'
                  ? ((p as any)[f.key] > 0 ? `$${(p as any)[f.key]}/mo` : 'Free')
                  : String((p as any)[f.key] || '-').replace(/^\d+[-\.]\s*/, '').replace(/^\d+-\d+\.\s*/, '')}
              </div>
            ))}
          </div>
        ))}

        {/* 운영버전 */}
        <div style={{ display: 'grid', gridTemplateColumns: gridCols, gap: '10px', padding: '7px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
          <div style={{ fontSize: '11px', color: '#666', fontFamily: 'monospace', display: 'flex', alignItems: 'center' }}>{tx('activeVersions')}</div>
          {products.map(p => {
            const vs = p.versions?.filter(v => v.is_active) || []
            return (
              <div key={p.id} style={{ textAlign: 'center' }}>
                <span className="font-display" style={{ color: 'var(--accent)', fontSize: '18px' }}>{vs.length}</span>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '3px', justifyContent: 'center', marginTop: '4px' }}>
                  {vs.slice(0, 2).map(v => <span key={v.id} className="badge badge-green" style={{ fontSize: '9px' }}>{v.version_name}</span>)}
                  {vs.length > 2 && <span className="badge badge-gray" style={{ fontSize: '9px' }}>+{vs.length - 2}</span>}
                </div>
              </div>
            )
          })}
        </div>

        {/* 구버전 */}
        <div style={{ display: 'grid', gridTemplateColumns: gridCols, gap: '10px', padding: '7px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
          <div style={{ fontSize: '11px', color: '#666', fontFamily: 'monospace', display: 'flex', alignItems: 'center' }}>{tx('deprVersions')}</div>
          {products.map(p => {
            const vs = p.versions?.filter(v => !v.is_active) || []
            return (
              <div key={p.id} style={{ textAlign: 'center' }}>
                <span style={{ fontSize: '16px', color: '#555' }}>{vs.length}</span>
              </div>
            )
          })}
        </div>

        {/* 전문가 분析 */}
        <div style={{ display: 'grid', gridTemplateColumns: gridCols, gap: '10px', padding: '10px 0', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
          <div style={{ fontSize: '11px', color: '#666', fontFamily: 'monospace' }}>{tx('expertAnalysis')}</div>
          {products.map(p => (
            <div key={p.id} style={{ fontSize: '11px', color: '#aaa', lineHeight: 1.6 }}>
              {(ko ? (p.description_ko || p.description) : p.description) || '-'}
            </div>
          ))}
        </div>

        {/* 구분 */}
        <div style={{ display: 'grid', gridTemplateColumns: gridCols, gap: '10px', padding: '7px 0' }}>
          <div style={{ fontSize: '11px', color: '#666', fontFamily: 'monospace', display: 'flex', alignItems: 'center' }}>{tx('status')}</div>
          {products.map(p => (
            <div key={p.id} style={{ textAlign: 'center' }}>
              {p.is_research_model
                ? <span className="badge badge-orange" style={{ fontSize: '10px' }}>{tx('researchModel')}</span>
                : <span className="badge badge-green" style={{ fontSize: '10px' }}>{tx('inService')}</span>
              }
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
